### ISSUE TITLE
jQuery vs Javascript

### ISSUE THREAD

**Issue by jsackett-303** [ecdestro/explorejson#1]
May want to consider using jQuery over raw Javascript for accessing your DOM [Have a look here](https://kinsta.com/knowledgebase/what-is-jquery/)

**Comment by ecdestro** [comment]
I'll look into cleaning this up with some jQuery magic this week.

**Comment by ecdestro** [comment]
Commits [#12](https://github.com/ecdestro/explorejson/commit/eb7ea74ca9b04e0990fcac29706e1e510a0c9fe3) and [#14](https://github.com/ecdestro/explorejson/commit/5b1cfdd3005076f7c958726df1353041d3b30c33) should have the updated jQuery code changes with better fetching and dynamic reloading of the sidebar on create, update, and deletes. Keeping this issue open for the time being in case there are other things that can be improved with this.

**Comment by jsackett-303** [comment]
Much more readable and more succinct! :+1:

**Comment by ecdestro** [comment]
For this project I'll consider this issue closed, and going forward see what jQuery and later React can do for me in terms of DOM manipulation and request routing. Thank you for the input!
