### ISSUE TITLE
JSON Objects tab not updating

### ISSUE THREAD

**Issue by jsackett-303** [ecdestro/explorejson#2]
Possible to update the object view after a 'Save Changes' on a json object?
![Screenshot from 2024-02-26 08-36-31](https://github.com/ecdestro/explorejson/assets/591507/493857c3-fdb1-4a88-a83b-640bf59c5bb5)

Note the update I made to an object name, but the name is not updated in the left column.

Also, a 'Delete Toy' click does not seem to work.

**Comment by ecdestro** [comment]
Looking up some basics on jquery - would it provide the methods for live updates to the Objects list?

**Comment by jsackett-303** [comment]
It sure does! In a more concise way than standard Javascript.

**Comment by jsackett-303** [comment]
'Add Toy' does work, but again does not update the index view on the left.

**Comment by ecdestro** [comment]
Quick and dirty fix to refresh the window on an add/update/delete. Fixed the delete functionality (req.params.toyId was being parsed as int when UUID is a string).
